name: Integration Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  ZIG_VERSION: 0.15.1

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}
          mirror: 'https://zigmirror.com'
      - name: Run integration tests
        run: zig build integration
